version: '3.7'
services:
  
  gcds-app:
    image: tiredofit/gcds:latest
    container_name: gcds-app
    volumes:
    - ./logs:/logs/
    - ./config:/assets/config
    environment:
    - DRY_RUN=TRUE
    - CONFIG_FILE=config.xml
    - DOMAIN=example.com
    - LDAP_PASS=password
    - LOG_LEVEL=ERROR
    - LOG_FILE=gcds-sync.log
    - MAIL_FROM=gcds@example.com
    - MAIL_TO=gcds@example.com
    - SMTP_HOST=smtp.example.com
    - SMTP_PORT=25
    - WEBHOOK_URL=https://example.com/webhook/12345678
    - WEBHOOK_CHANNEL=#general
    - ZABBIX_HOSTNAME=gcds-app
    networks:
    - internal
    - services
    restart: always

networks:
  internal:
    external: false
  services:
    external: true

